import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { mkdirSync,readFileSync,writeFileSync,readdirSync } from 'node:fs';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';
import ts from 'typescript';
const output=resolve('.runtime/tests');mkdirSync(output,{recursive:true});
writeFileSync(output+'/env.mjs','export const env=globalThis.__musicTestEnv;');
const modules={'lib/monetization.ts':'monetization','app/ads.txt/route.ts':'ads-txt','app/api/health/route.ts':'health','lib/contracts.ts':'contracts','lib/server.ts':'server','lib/providers.ts':'providers','lib/recognition.ts':'recognition','lib/scan.ts':'scan','lib/scan-store.ts':'scan-store','lib/creator.ts':'creator','lib/creator-store.ts':'creator-store','lib/product-events.ts':'product-events','app/api/creator/route.ts':'creator-route','app/api/creator/assistant/route.ts':'assistant-route','app/api/events/route.ts':'events-route','app/api/insights/route.ts':'insights-route','app/api/scans/route.ts':'scans-route','app/api/scans/segment/route.ts':'segment-route','app/api/recognize/route.ts':'recognize','app/api/search/route.ts':'search','app/api/saved/route.ts':'saved','app/api/config/route.ts':'config'};
for(const [path,name] of Object.entries(modules)){
 const source=readFileSync(path,'utf8').replace(/(['"])(?:@\/lib\/|\.\/)(contracts|server|providers|recognition|scan|scan-store|monetization|creator|creator-store|product-events)\1/g,(_,quote,name)=>quote+'./'+name+'.mjs'+quote).replaceAll("'cloudflare:workers'","'./env.mjs'");
 writeFileSync(output+'/'+name+'.mjs',ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText);
}
class Statement{
 constructor(database,sql,args=[]){this.database=database;this.sql=sql;this.args=args;}
 bind(...args){return new Statement(this.database,this.sql,args);}
 async first(){return this.database.prepare(this.sql).get(...this.args)||null;}
 async all(){return {results:this.database.prepare(this.sql).all(...this.args)};}
 async run(){return {success:true,meta:this.database.prepare(this.sql).run(...this.args)};}
}
function d1(database){return {prepare:sql=>new Statement(database,sql),batch:async statements=>{database.exec('BEGIN');try{const result=[];for(const s of statements)result.push(await s.run());database.exec('COMMIT');return result;}catch(e){database.exec('ROLLBACK');throw e;}}};}
let database;let upstreamCalls=0;let responder;
globalThis.__musicTestEnv={};
const env=globalThis.__musicTestEnv;
function reset(){database?.close();database=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())database.exec(readFileSync('drizzle/'+f,'utf8'));for(const key of Object.keys(env))delete env[key];Object.assign(env,{DB:d1(database),AUDD_API_TOKEN:'private-test-fixture',TESTER_ACCESS_KEY:'owner-testing-key-123456',GLOBAL_DAILY_SCAN_LIMIT:'100',VISITOR_DAILY_SCAN_LIMIT:'5',IP_DAILY_SCAN_LIMIT:'20'});upstreamCalls=0;responder=()=>Response.json({status:'success',result:{title:'Fixture Song',artist:'Fixture Artist',album:'Fixture Album',spotify:{id:'fixture',external_urls:{spotify:'https://open.spotify.com/track/fixture'}}}});}
const originalFetch=globalThis.fetch;
globalThis.fetch=async(...args)=>{upstreamCalls++;return responder(...args);};
const contracts=await import(pathToFileURL(output+'/contracts.mjs'));
const recognition=await import(pathToFileURL(output+'/recognize.mjs'));
const saved=await import(pathToFileURL(output+'/saved.mjs'));
const config=await import(pathToFileURL(output+'/config.mjs'));
const search=await import(pathToFileURL(output+'/search.mjs'));
const scans=await import(pathToFileURL(output+'/scans-route.mjs'));
const segmentRoute=await import(pathToFileURL(output+'/segment-route.mjs'));
const scan=await import(pathToFileURL(output+'/scan.mjs'));
const ads=await import(pathToFileURL(output+'/ads-txt.mjs'));
const health=await import(pathToFileURL(output+'/health.mjs'));
const visitor='11111111-1111-4111-8111-111111111111';
function wav(seconds=3,value=100){const data=new ArrayBuffer(44+Math.ceil(seconds*22050)*2);const v=new DataView(data);const str=(n,s)=>{for(let i=0;i<s.length;i++)v.setUint8(n+i,s.charCodeAt(i));};str(0,'RIFF');v.setUint32(4,data.byteLength-8,true);str(8,'WAVE');str(12,'fmt ');v.setUint32(16,16,true);v.setUint16(20,1,true);v.setUint16(22,1,true);v.setUint32(24,22050,true);v.setUint32(28,44100,true);v.setUint16(32,2,true);v.setUint16(34,16,true);str(36,'data');v.setUint32(40,data.byteLength-44,true);v.setInt16(44,value,true);return data;}
function request(body=wav(),options={}){return new Request('https://music.example/api/recognize',{method:'POST',headers:{'content-type':'audio/wav','idempotency-key':options.key||crypto.randomUUID(),cookie:'ws_visitor='+(options.visitor||visitor),'cf-connecting-ip':options.ip||'203.0.113.1',origin:'https://music.example',...options.headers},body});}
await test('cost and privacy boundaries',async t=>{
 await t.test('rejects internal, credentialed, non-HTTPS and social-page links',()=>{for(const u of ['http://example.com/a.mp3','https://127.0.0.1/a.mp3','https://2130706433/a.mp3','https://[::1]/a.mp3','https://a:b@example.com/a.mp3','https://localhost/a.mp3','https://foo.local/a.mp3','https://youtube.com/watch?v=123'])assert.throws(()=>contracts.validateMediaURL(u));assert.equal(contracts.validateMediaURL('https://cdn.example.com/a.mp3#t=2'),'https://cdn.example.com/a.mp3');});
 await t.test('server checks real WAV duration and format',()=>{assert.equal(contracts.parsePCM(wav()),3);assert.throws(()=>contracts.parsePCM(wav(13)));assert.throws(()=>contracts.parsePCM(wav(1)));const data=wav();new DataView(data).setUint16(22,2,true);assert.throws(()=>contracts.parsePCM(data));assert.throws(()=>contracts.parsePCM(new ArrayBuffer(20)));});
 await t.test('CSV export neutralizes spreadsheet formulas',()=>{assert.equal(contracts.csvCell('=HYPERLINK("bad")'),'"\'=HYPERLINK(""bad"")"');assert.equal(contracts.csvCell('a,b'),'"a,b"');});
 await t.test('missing provider and public test token fail closed without a charge',async()=>{reset();env.AUDD_API_TOKEN='';assert.equal((await recognition.POST(request())).status,503);env.AUDD_API_TOKEN='test';assert.equal((await recognition.POST(request())).status,503);assert.equal(upstreamCalls,0);});
 await t.test('invalid audio and cross-origin requests never call provider',async()=>{reset();assert.equal((await recognition.POST(request(new ArrayBuffer(20)))).status,400);assert.equal((await recognition.POST(request(wav(),{headers:{origin:'https://evil.example'}}))).status,403);assert.equal(upstreamCalls,0);});
 await t.test('real handler normalizes a provider match and saves it privately',async()=>{reset();const response=await recognition.POST(request());assert.equal(response.status,200);const body=await response.json();assert.equal(body.song.title,'Fixture Song');assert.equal(body.song.source,'recognition');assert.equal(upstreamCalls,1);const same=await saved.GET(new Request('https://music.example/api/saved',{headers:{cookie:'ws_visitor='+visitor}}));assert.equal((await same.json()).songs.length,1);const other=await saved.GET(new Request('https://music.example/api/saved'));assert.equal((await other.json()).songs.length,0);});
 await t.test('duplicate audio reuses a result without billing and preserves new position',async()=>{reset();await recognition.POST(request());const r=await recognition.POST(request(wav(),{headers:{'x-sample-start':'42'}}));const result=await r.json();assert.equal(result.cached,true);assert.equal(result.song.sampleAt,42);assert.equal(upstreamCalls,1);});
 await t.test('same idempotency key cannot issue a second provider request on failure',async()=>{reset();responder=()=>{throw new Error('upstream timeout');};const key=crypto.randomUUID();assert.equal((await recognition.POST(request(wav(),{key}))).status,503);const again=await recognition.POST(request(wav(),{key}));assert.match((await again.json()).error,/did not finish/);assert.equal(upstreamCalls,1);});
 await t.test('per-visitor cap holds across distinct clips',async()=>{reset();env.VISITOR_DAILY_SCAN_LIMIT='2';for(let i=0;i<2;i++)assert.equal((await recognition.POST(request(wav(3,i+1)))).status,200);assert.equal((await recognition.POST(request(wav(3,77)))).status,429);assert.equal(upstreamCalls,2);});
 await t.test('authenticated tester bypasses visitor, IP, global and total app quotas without exposing the key',async()=>{reset();env.VISITOR_DAILY_SCAN_LIMIT='1';env.IP_DAILY_SCAN_LIMIT='1';env.GLOBAL_DAILY_SCAN_LIMIT='1';env.TOTAL_SCAN_LIMIT='0';const headers={'x-tester-key':env.TESTER_ACCESS_KEY};for(let i=0;i<3;i++)assert.equal((await recognition.POST(request(wav(3,150+i),{headers}))).status,200);assert.equal(upstreamCalls,3);assert.equal(database.prepare("SELECT used FROM recognition_meter WHERE id='global'").get().used,0);const cfg=await config.GET(new Request('https://music.example/api/config',{headers:{cookie:'ws_visitor='+visitor,'cf-connecting-ip':'203.0.113.1',...headers}}));const body=await cfg.json();assert.equal(body.tester,true);assert.equal(body.remainingScans,1000000);assert.ok(!JSON.stringify(body).includes(env.TESTER_ACCESS_KEY));});
 await t.test('global cap holds across visitors and IP addresses',async()=>{reset();env.GLOBAL_DAILY_SCAN_LIMIT='1';assert.equal((await recognition.POST(request())).status,200);assert.equal((await recognition.POST(request(wav(3,66),{visitor:crypto.randomUUID(),ip:'203.0.113.2'}))).status,429);assert.equal(upstreamCalls,1);});
 await t.test('IP cap holds after cookie reset',async()=>{reset();env.IP_DAILY_SCAN_LIMIT='1';await recognition.POST(request());assert.equal((await recognition.POST(request(wav(3,66),{visitor:crypto.randomUUID()}))).status,429);assert.equal(upstreamCalls,1);});
 await t.test('parallel duplicate request bills at most once',async()=>{reset();const ready=responder;responder=async()=>{await new Promise(resolve=>setTimeout(resolve,20));return ready();};const key=crypto.randomUUID();const responses=await Promise.all([recognition.POST(request(wav(),{key})),recognition.POST(request(wav(),{key}))]);assert.equal(upstreamCalls,1);assert.equal(responses.filter(r=>r.status===200).length,1);});
 await t.test('global reservation stays bounded with competing concurrent scans',async()=>{reset();env.GLOBAL_DAILY_SCAN_LIMIT='1';const responses=await Promise.all([recognition.POST(request(wav(3,1))),recognition.POST(request(wav(3,2),{visitor:crypto.randomUUID(),ip:'203.0.113.2'}))]);assert.equal(upstreamCalls,1);assert.equal(responses.filter(r=>r.status===200).length,1);});
 await t.test('catalog results are real-provider-shaped, sanitized and cached',async()=>{reset();responder=()=>Response.json({results:[{trackId:1,trackName:'Song',artistName:'Artist',trackViewUrl:'javascript:alert(1)',artworkUrl100:'https://evil.example/pixel'}]});const response=await search.GET(new Request('https://music.example/api/search?q=Song'));const data=await response.json();assert.equal(data.songs[0].source,'catalog');assert.equal(data.songs[0].apple,undefined);assert.equal(data.songs[0].artwork,undefined);await search.GET(new Request('https://music.example/api/search?q=Song'));assert.equal(upstreamCalls,1);});
 await t.test('public config never exposes credentials',async()=>{reset();const response=await config.GET(new Request('https://music.example/api/config'));const body=await response.text();assert.ok(!body.includes(env.AUDD_API_TOKEN));assert.ok(!body.includes(env.TESTER_ACCESS_KEY));assert.match(response.headers.get('set-cookie'),/HttpOnly; SameSite=Strict/);});
 await t.test('saved collection is bounded, owner isolated and can be cleared',async()=>{reset();for(let i=0;i<102;i++){const r=await saved.POST(new Request('https://music.example/api/saved',{method:'POST',headers:{cookie:'ws_visitor='+visitor,'content-type':'application/json'},body:JSON.stringify({id:String(i),title:'Song '+i,artist:'Artist',source:'catalog'})}));assert.equal(r.status,200);}assert.equal(database.prepare('SELECT COUNT(*) AS n FROM saved').get().n,100);const foreign=await saved.DELETE(new Request('https://music.example/api/saved',{method:'DELETE'}));assert.equal(foreign.status,200);assert.equal(database.prepare('SELECT COUNT(*) AS n FROM saved').get().n,100);await saved.DELETE(new Request('https://music.example/api/saved',{method:'DELETE',headers:{cookie:'ws_visitor='+visitor}}));assert.equal(database.prepare('SELECT COUNT(*) AS n FROM saved').get().n,0);});
});

function scanInput(options={}){return {id:crypto.randomUUID(),fileHash:'a'.repeat(64),filename:'Fixture recording.wav',durationMs:36000,mode:'continuous',samples:3,...options};}
function scanRequest(input,options={}){return new Request('https://music.example/api/scans'+(options.query||''),{method:options.method||'POST',headers:{origin:'https://music.example','content-type':'application/json',cookie:'ws_visitor='+(options.visitor||visitor),'cf-connecting-ip':'203.0.113.1',...options.headers},...(input?{body:JSON.stringify(input)}:{})});}
function scanSegment(input,index,body=wav(12,100+index),options={}){return new Request(`https://music.example/api/scans/segment?id=${input.id}&index=${index}`,{method:'POST',headers:{origin:'https://music.example','content-type':'audio/wav','x-source-sha256':input.fileHash,cookie:'ws_visitor='+(options.visitor||visitor),'cf-connecting-ip':'203.0.113.1',...options.headers},body});}
async function createScan(input){const r=await scans.POST(scanRequest(input));assert.equal(r.status,201,await r.clone().text());return (await r.json()).job;}
async function getScan(input,who=visitor){const r=await scans.GET(scanRequest(null,{method:'GET',query:'?id='+input.id,visitor:who}));assert.equal(r.status,200);return (await r.json()).job;}
await test('persistent video scans and honest coverage',async t=>{
 await t.test('continuous plans cover every millisecond with valid bounded windows',()=>{for(const duration of [2000,12000,12001,13000,24001,45000,123456,1200000]){const windows=scan.planScan(duration,'continuous',5);assert.equal(windows.length,Math.ceil(duration/12000));assert.equal(windows[0].startMs,0);assert.equal(windows.at(-1).endMs,duration);assert.equal(scan.intervalCoverage(windows),duration);for(let i=0;i<windows.length;i++){assert.ok(windows[i].endMs-windows[i].startMs>=2000);assert.ok(windows[i].endMs-windows[i].startMs<=12000);if(i)assert.equal(windows[i].startMs,windows[i-1].endMs);}}const survey=scan.planScan(600000,'survey',5);assert.equal(survey.length,5);assert.equal(scan.intervalCoverage(survey),60000);assert.equal(survey.at(-1).endMs,600000);});
 await t.test('timeline merges adjacent matches without inventing coverage across gaps or failures',()=>{const song={id:'A',title:'Song A',artist:'Artist',source:'recognition'};const match=(startMs,endMs)=>({startMs,endMs,state:'matched',result:{song}});const hits=scan.timelineHits([match(0,12000),match(12000,24000),match(36000,48000),{startMs:48000,endMs:60000,state:'no_match'},match(60000,72000)]);assert.equal(hits.length,3);assert.equal(hits[0].endMs,24000);assert.equal(hits[0].samples,2);assert.equal(hits[1].startMs,36000);assert.equal(hits[2].startMs,60000);});
 await t.test('plans fail closed without a provider and reject unaffordable full coverage',async()=>{reset();env.AUDD_API_TOKEN='';assert.equal((await scans.POST(scanRequest(scanInput()))).status,503);env.AUDD_API_TOKEN='private-fixture';assert.equal((await scans.POST(scanRequest(scanInput({durationMs:120000})))).status,429);assert.equal(database.prepare('SELECT COUNT(*) n FROM scan_jobs').get().n,0);assert.equal(upstreamCalls,0);});
 await t.test('scan creation is idempotent, immutable, and private',async()=>{reset();const input=scanInput();await createScan(input);assert.equal((await scans.POST(scanRequest(input))).status,200);assert.equal((await scans.POST(scanRequest({...input,filename:'Changed'}))).status,409);assert.equal((await scans.GET(scanRequest(null,{method:'GET',query:'?id='+input.id,visitor:crypto.randomUUID()}))).status,404);assert.equal((await segmentRoute.POST(scanSegment(input,0,wav(12),{visitor:crypto.randomUUID()}))).status,404);assert.equal((await segmentRoute.POST(scanSegment(input,0,wav(12),{headers:{'x-source-sha256':'b'.repeat(64)}}))).status,409);assert.equal((await segmentRoute.POST(scanSegment(input,0,wav(3)))).status,400);assert.equal(upstreamCalls,0);});
 await t.test('three-section job persists, resumes and produces a grouped two-song timeline',async()=>{reset();const input=scanInput();await createScan(input);responder=()=>Response.json({status:'success',result:{title:upstreamCalls<3?'First Song':'Second Song',artist:'Fixture Artist'}});const first=await segmentRoute.POST(scanSegment(input,0));assert.equal(first.status,200);assert.equal((await getScan(input)).segments[0].state,'matched');await segmentRoute.POST(scanSegment(input,0));assert.equal(upstreamCalls,1);for(const i of [1,2])assert.equal((await segmentRoute.POST(scanSegment(input,i))).status,200);const job=await getScan(input);const stats=scan.scanStats(job);assert.equal(stats.completed,3);assert.equal(stats.checkedMs,36000);assert.equal(stats.providerCalls,3);assert.equal(scan.timelineHits(job.segments).length,2);assert.equal(scan.timelineHits(job.segments)[0].endMs,24000);assert.match(scan.scanCSV(job),/First Song/);assert.equal((await scans.GET(scanRequest(null,{method:'GET'}))).status,200);});
 await t.test('silence uses no provider call and is separate from recognition coverage',async()=>{reset();const input=scanInput({durationMs:4000});await createScan(input);await segmentRoute.POST(scanSegment(input,0,wav(4,0)));const stats=scan.scanStats(await getScan(input));assert.equal(upstreamCalls,0);assert.equal(stats.silentMs,4000);assert.equal(stats.checkedMs,0);assert.equal(stats.providerCalls,0);});
 await t.test('identical audio in distinct windows reuses the cache without losing positions',async()=>{reset();const input=scanInput({durationMs:24000});await createScan(input);await segmentRoute.POST(scanSegment(input,0,wav(12,77)));await segmentRoute.POST(scanSegment(input,1,wav(12,77)));const job=await getScan(input);assert.equal(upstreamCalls,1);assert.equal(job.segments[1].result.song.sampleAt,12);assert.equal(scan.scanStats(job).cacheHits,1);});
 await t.test('quota exhaustion preserves a pending section for safe later resume',async()=>{reset();const input=scanInput();await createScan(input);env.GLOBAL_DAILY_SCAN_LIMIT='1';await segmentRoute.POST(scanSegment(input,0));assert.equal((await segmentRoute.POST(scanSegment(input,1))).status,429);assert.equal((await getScan(input)).segments[1].state,'pending');assert.equal(upstreamCalls,1);env.GLOBAL_DAILY_SCAN_LIMIT='3';assert.equal((await segmentRoute.POST(scanSegment(input,1))).status,200);assert.equal(upstreamCalls,2);});
 await t.test('competing tabs cannot bill the same scan section twice',async()=>{reset();const input=scanInput();await createScan(input);const original=responder;responder=async()=>{await new Promise(resolve=>setTimeout(resolve,20));return original();};await Promise.all([segmentRoute.POST(scanSegment(input,0)),segmentRoute.POST(scanSegment(input,0))]);assert.equal(upstreamCalls,1);assert.equal((await getScan(input)).segments[0].state,'matched');});
 await t.test('a lost response is recovered from the paid operation without another request',async()=>{reset();const input=scanInput();await createScan(input);await segmentRoute.POST(scanSegment(input,0));database.prepare("UPDATE scan_segments SET state='processing',result=NULL WHERE job_id=? AND ordinal=0").run(input.id);const job=await getScan(input);assert.equal(job.segments[0].state,'matched');assert.equal(job.segments[0].result.song.title,'Fixture Song');assert.equal(upstreamCalls,1);});
 await t.test('provider errors stay unresolved and are never retried automatically',async()=>{reset();const input=scanInput();await createScan(input);responder=()=>{throw new Error('timeout');};assert.equal((await segmentRoute.POST(scanSegment(input,0))).status,503);assert.equal((await segmentRoute.POST(scanSegment(input,0))).status,200);assert.equal(upstreamCalls,1);const job=await getScan(input);assert.equal(job.segments[0].state,'error');assert.equal(scan.scanStats(job).checkedMs,0);assert.equal(scan.scanStats(job).providerCalls,1);});
 await t.test('abandoned claims become uncertain instead of being charged again',async()=>{reset();const input=scanInput();await createScan(input);database.prepare("UPDATE scan_segments SET state='processing',claimed=1 WHERE job_id=? AND ordinal=0").run(input.id);const job=await getScan(input);assert.equal(job.segments[0].state,'error');assert.match(job.segments[0].result.error,/unknown/);assert.equal(upstreamCalls,0);});
 await t.test('deletion is private, cascades to sections, and expired jobs are inaccessible',async()=>{reset();const input=scanInput();await createScan(input);await scans.DELETE(scanRequest(null,{method:'DELETE',query:'?id='+input.id,visitor:crypto.randomUUID()}));assert.equal(database.prepare('SELECT COUNT(*) n FROM scan_segments').get().n,3);database.prepare('UPDATE scan_jobs SET expires=0 WHERE id=?').run(input.id);assert.equal((await scans.GET(scanRequest(null,{method:'GET',query:'?id='+input.id}))).status,404);await scans.DELETE(scanRequest(null,{method:'DELETE',query:'?id='+input.id}));assert.equal(database.prepare('SELECT COUNT(*) n FROM scan_segments').get().n,0);});
});
await test('free launch and publisher verification',async t=>{
 await t.test('total budget survives request cleanup and rolling allowance resets',async()=>{reset();env.TOTAL_SCAN_LIMIT='1';await recognition.POST(request());assert.equal(database.prepare("SELECT used FROM recognition_meter WHERE id='global'").get().used,1);database.exec('DELETE FROM operations; DELETE FROM cache;');assert.equal((await recognition.POST(request(wav(3,201)))).status,429);const body=await(await config.GET(new Request('https://music.example/api/config'))).json();assert.equal(body.remainingScans,0);assert.equal(upstreamCalls,1);});
 await t.test('concurrent visitors cannot exceed the total budget',async()=>{reset();env.TOTAL_SCAN_LIMIT='1';const responses=await Promise.all([recognition.POST(request(wav(3,100))),recognition.POST(request(wav(3,101),{visitor:crypto.randomUUID(),ip:'203.0.113.2'}))]);assert.equal(responses.filter(r=>r.status===200).length,1);assert.equal(upstreamCalls,1);assert.equal(database.prepare("SELECT used FROM recognition_meter WHERE id='global'").get().used,1);});
 await t.test('plans, silence, cache hits and duplicate replies do not consume total provider budget',async()=>{reset();env.TOTAL_SCAN_LIMIT='1';const input=scanInput({durationMs:4000});await createScan(input);await segmentRoute.POST(scanSegment(input,0,wav(4,0)));assert.equal(database.prepare("SELECT used FROM recognition_meter WHERE id='global'").get().used,0);const key=crypto.randomUUID();await recognition.POST(request(wav(3,130),{key}));await recognition.POST(request(wav(3,130),{key}));await recognition.POST(request(wav(3,130)));assert.equal(upstreamCalls,1);assert.equal(database.prepare("SELECT used FROM recognition_meter WHERE id='global'").get().used,1);});
 await t.test('provider errors consume budget and only a deliberate ceiling increase restores requests',async()=>{reset();env.TOTAL_SCAN_LIMIT='1';const success=responder;responder=()=>{throw new Error('timeout');};assert.equal((await recognition.POST(request())).status,503);responder=success;assert.equal((await recognition.POST(request(wav(3,201)))).status,429);env.TOTAL_SCAN_LIMIT='2';assert.equal((await recognition.POST(request(wav(3,201)))).status,200);assert.equal(upstreamCalls,2);assert.equal(database.prepare("SELECT used FROM recognition_meter WHERE id='global'").get().used,2);});
 await t.test('publisher verification rejects empty, placeholder and injected IDs without any outbound request',async()=>{reset();for(const id of ['', 'ca-pub-0000000000000000','pub-1234567890123456','ca-pub-1234567890123456\nother.com,evil,DIRECT','<script>']){env.ADSENSE_CLIENT_ID=id;assert.equal((await ads.GET()).status,404);}env.ADSENSE_CLIENT_ID='ca-pub-1234567890123456';const response=await ads.GET();assert.equal(response.status,200);assert.equal(await response.text(),'google.com, pub-1234567890123456, DIRECT, f08c47fec0942fa0\n');assert.match(response.headers.get('content-type'),/text\/plain/);assert.equal(upstreamCalls,0);});
 await t.test('health distinguishes missing recognition, configured recognition and budget pause without charging',async()=>{reset();env.AUDD_API_TOKEN='  ';assert.equal((await(await health.GET()).json()).recognition,'awaiting_activation');env.AUDD_API_TOKEN=' test ';assert.equal((await(await health.GET()).json()).recognition,'awaiting_activation');env.AUDD_API_TOKEN='private-fixture';assert.equal((await(await health.GET()).json()).recognition,'configured');env.TOTAL_SCAN_LIMIT='0';const status=await(await health.GET()).json();assert.equal(status.recognition,'paused');assert.equal(status.visitorBilling,'none');assert.equal(upstreamCalls,0);});
});
const creator=await import(pathToFileURL(output+'/creator.mjs'));
const creatorRoute=await import(pathToFileURL(output+'/creator-route.mjs'));
const assistantRoute=await import(pathToFileURL(output+'/assistant-route.mjs'));
const eventRoute=await import(pathToFileURL(output+'/events-route.mjs'));
const insightsRoute=await import(pathToFileURL(output+'/insights-route.mjs'));
function creatorRequest(body,options={}){return new Request('https://music.example/api/creator'+(options.query||''),{method:options.method||'POST',headers:{origin:'https://music.example','content-type':'application/json',cookie:'ws_visitor='+(options.visitor||visitor),'cf-connecting-ip':'203.0.113.1',...options.headers},...(body?{body:JSON.stringify(body)}:{})});}
async function matchedProject(){const input=scanInput({durationMs:12000,samples:1});await createScan(input);await segmentRoute.POST(scanSegment(input,0,wav(12,66)));const job=await getScan(input);return {input,job,songId:job.segments[0].result.song.id};}
const decision=(songId,changes={})=>({songId,action:'licensed',notes:'License reference, YouTube channel scope and expiry reviewed by creator.',licenseUrl:'https://example.com/license/fixture',attribution:'Fixture Song by Fixture Artist — licensed credit',...changes});
await test('creator report and private review workflow',async t=>{
 await t.test('reports preserve gaps, no-matches, pending windows and rejected recordings',async()=>{reset();const input=scanInput({durationMs:60000,mode:'survey',samples:2});await createScan(input);await segmentRoute.POST(scanSegment(input,0,wav(12,66)));const job=await getScan(input);const songId=job.segments[0].result.song.id;let review={...creator.emptyReview(),decisions:[decision(songId,{action:'wrong_match'})]};const r=creator.creatorReport(job,review);assert.equal(r.coveragePercent,20);assert.equal(r.gapMs,36000);assert.equal(r.unresolved.length,1);assert.equal(r.wrongMatches,1);assert.match(creator.reportText(job,review),/Not sampled/);assert.match(creator.reportCSV(job,review),/not_sampled/);assert.doesNotMatch(creator.musicCredits(r),/licensed credit/);job.segments[1].state='no_match';assert.equal(creator.creatorReport(job,review).unmatched.length,1);assert.match(creator.answerReport(job,review,'What was missed?'),/No match does not establish absence/);});
 await t.test('license decisions require evidence, refer to real returned recordings and reject duplicate track entries',async()=>{reset();const {input,songId}=await matchedProject();const invalid=[decision(songId,{notes:'',licenseUrl:''}),decision('audd:not-in-this-scan')];for(const d of invalid)assert.equal((await creatorRoute.POST(creatorRequest({id:input.id,expectedRevision:0,review:{...creator.emptyReview(),decisions:[d]}}))).status,400);assert.equal((await creatorRoute.POST(creatorRequest({id:input.id,expectedRevision:0,review:{...creator.emptyReview(),decisions:[decision(songId),decision(songId)]}}))).status,400);assert.equal((await creatorRoute.POST(creatorRequest({id:input.id,expectedRevision:0,review:{...creator.emptyReview(),decisions:[decision(songId,{licenseUrl:'javascript:alert(1)'})]}}))).status,400);});
 await t.test('saved reviews survive reload and stale or parallel changes cannot overwrite another tab',async()=>{reset();const {input,songId}=await matchedProject();const body={id:input.id,expectedRevision:0,review:{...creator.emptyReview(),notes:'Editor handoff',decisions:[decision(songId)]}};const replies=await Promise.all([creatorRoute.POST(creatorRequest(body)),creatorRoute.POST(creatorRequest({...body,review:{...body.review,notes:'Other tab'}}))]);assert.equal(replies.filter(r=>r.status===200).length,1);assert.equal(replies.filter(r=>r.status===409).length,1);const loaded=await(await creatorRoute.GET(creatorRequest(null,{method:'GET',query:'?id='+input.id}))).json();assert.equal(loaded.revision,1);assert.equal(loaded.review.decisions[0].action,'licensed');assert.equal(upstreamCalls,1);});
 await t.test('reviews and library are isolated and notes are explicitly scoped by platform',async()=>{reset();const {input,songId}=await matchedProject();const stranger=crypto.randomUUID();assert.equal((await creatorRoute.GET(creatorRequest(null,{method:'GET',query:'?id='+input.id,visitor:stranger}))).status,404);const body={id:input.id,expectedRevision:0,review:{...creator.emptyReview(),decisions:[decision(songId)]},rememberSongId:songId};assert.equal((await creatorRoute.POST(creatorRequest(body,{visitor:stranger}))).status,404);assert.equal((await creatorRoute.POST(creatorRequest(body))).status,200);const mine=await(await creatorRoute.GET(creatorRequest(null,{method:'GET'}))).json();assert.equal(mine.library.length,1);assert.equal(mine.library[0].platform,'youtube');assert.equal((await(await creatorRoute.GET(creatorRequest(null,{method:'GET',visitor:stranger}))).json()).library.length,0);await creatorRoute.DELETE(creatorRequest(null,{method:'DELETE',query:'?noteId='+mine.library[0].id,visitor:stranger}));assert.equal(database.prepare('SELECT COUNT(*) n FROM license_notes').get().n,1);await creatorRoute.DELETE(creatorRequest(null,{method:'DELETE',query:'?noteId='+mine.library[0].id}));assert.equal(database.prepare('SELECT COUNT(*) n FROM license_notes').get().n,0);assert.equal((await(await creatorRoute.GET(creatorRequest(null,{method:'GET',query:'?id='+input.id}))).json()).review.decisions.length,1);});
 await t.test('expired projects and cross-origin writes fail without recognition or AI calls',async()=>{reset();const {input,songId}=await matchedProject();const body={id:input.id,expectedRevision:0,review:{...creator.emptyReview(),decisions:[decision(songId)]}};assert.equal((await creatorRoute.POST(creatorRequest(body,{headers:{origin:'https://evil.example'}}))).status,403);database.prepare('UPDATE scan_jobs SET expires=0 WHERE id=?').run(input.id);assert.equal((await creatorRoute.POST(creatorRequest(body))).status,404);assert.equal((await assistantRoute.POST(creatorRequest({id:input.id,question:'What should I review?'}))).status,404);assert.equal(upstreamCalls,1);});
 await t.test('CSV exports neutralize formulas and credits use the entered licensed attribution only',()=>{reset();const job={...scanInput({filename:'=HYPERLINK("bad")',durationMs:12000,samples:1}),created:1,expires:9999999999,segments:[{index:0,startMs:0,endMs:12000,state:'matched',result:{song:{id:'x',title:'=malicious',artist:'Artist',source:'recognition'},providerCalls:0,cached:true,provider:'audd',latencyMs:0}}]};const review={...creator.emptyReview(),decisions:[decision('x',{attribution:'Exact licensed credit'})]};assert.match(creator.reportCSV(job,review),/"'=HYPERLINK/);assert.equal(creator.musicCredits(creator.creatorReport(job,review)),'Exact licensed credit');});
});
await test('bounded optional report writing and product measurements',async t=>{
 await t.test('reports and guide work with no AI key and never send audio or trigger another recognition',async()=>{reset();const {input}=await matchedProject();for(const useAI of [false,true]){const response=await assistantRoute.POST(creatorRequest({id:input.id,question:'What should I review?',useAI}));assert.equal(response.status,200);const body=await response.json();assert.equal(body.engine,'rules');assert.match(body.answer,/1 different recordings/);}assert.equal(upstreamCalls,1);});
 await t.test('AI drafts are bounded, metadata-only, cached and counted once',async()=>{reset();const {input}=await matchedProject();env.OPENAI_API_KEY='private-ai-fixture';env.CREATOR_AI_ENABLED='true';let sent;responder=(_,options)=>{sent=JSON.parse(options.body);return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Review the returned recording and listen to unsampled gaps.'}]}],usage:{input_tokens:101,output_tokens:12}});};const body={id:input.id,question:'What should I review?',useAI:true};const first=await(await assistantRoute.POST(creatorRequest(body))).json();const second=await(await assistantRoute.POST(creatorRequest(body))).json();assert.equal(first.engine,'openai');assert.equal(second.cached,true);assert.equal(upstreamCalls,2);assert.equal(sent.store,false);assert.equal(sent.max_output_tokens,800);assert.ok(!sent.input.includes(input.fileHash));assert.ok(!sent.input.includes(input.filename));assert.equal(database.prepare("SELECT used FROM recognition_meter WHERE id='creator_ai'").get().used,1);});
 await t.test('concurrent AI drafts cannot issue the same paid request twice',async()=>{reset();const {input}=await matchedProject();env.OPENAI_API_KEY='private-ai-fixture';env.CREATOR_AI_ENABLED='true';responder=async()=>{await new Promise(r=>setTimeout(r,20));return Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Review the music and saved decisions.'}]}]});};const body={id:input.id,question:'Explain the report',useAI:true};await Promise.all([assistantRoute.POST(creatorRequest(body)),assistantRoute.POST(creatorRequest(body))]);assert.equal(upstreamCalls,2);});
 await t.test('AI cumulative ceiling survives operation cleanup and failures fall back without retry',async()=>{reset();const {input}=await matchedProject();env.OPENAI_API_KEY='private-ai-fixture';env.CREATOR_AI_ENABLED='true';env.CREATOR_AI_TOTAL_LIMIT='1';responder=()=>{throw new Error('upstream unavailable');};const body={id:input.id,question:'Explain the report',useAI:true};assert.equal((await(await assistantRoute.POST(creatorRequest(body))).json()).engine,'rules');await assistantRoute.POST(creatorRequest(body));assert.equal(upstreamCalls,2);database.exec("DELETE FROM operations WHERE kind='creator_ai'");await assistantRoute.POST(creatorRequest({...body,question:'What should I review?'}));assert.equal(upstreamCalls,2);assert.equal(database.prepare("SELECT used FROM recognition_meter WHERE id='creator_ai'").get().used,1);});
 await t.test('AI completion with an unsafe clearance claim is discarded',async()=>{reset();const {input}=await matchedProject();env.OPENAI_API_KEY='private-ai-fixture';env.CREATOR_AI_ENABLED='true';responder=()=>Response.json({status:'completed',output:[{type:'message',content:[{type:'output_text',text:'Your video is guaranteed safe.'}]}]});const answer=await(await assistantRoute.POST(creatorRequest({id:input.id,question:'Is it safe?',useAI:true}))).json();assert.equal(answer.engine,'rules');assert.doesNotMatch(answer.answer,/guaranteed safe/);});
 await t.test('events require owned projects, preserve privacy, deduplicate views, and operator metrics require the tester key',async()=>{reset();const {input}=await matchedProject();for(let i=0;i<2;i++)assert.equal((await eventRoute.POST(creatorRequest({kind:'report_opened',jobId:input.id}))).status,200);assert.equal(database.prepare("SELECT COUNT(*) n FROM product_events WHERE kind='report_opened'").get().n,1);assert.equal((await eventRoute.POST(creatorRequest({kind:'feedback',jobId:input.id,value:'txt'}))).status,400);assert.equal((await eventRoute.POST(creatorRequest({kind:'feedback',jobId:input.id,value:'wrong_matches'},{visitor:crypto.randomUUID()}))).status,404);await eventRoute.POST(creatorRequest({kind:'feedback',jobId:input.id,value:'useful'}));assert.equal((await insightsRoute.GET(creatorRequest(null,{method:'GET'}))).status,403);const insights=await insightsRoute.GET(creatorRequest(null,{method:'GET',headers:{'x-tester-key':env.TESTER_ACCESS_KEY}}));assert.equal(insights.status,200);const data=await insights.json();assert.equal(data.jobs.matched,1);assert.equal(data.events.find(e=>e.kind==='feedback').count,1);assert.ok(!JSON.stringify(data).includes(env.TESTER_ACCESS_KEY));});
});
globalThis.fetch=originalFetch;database?.close();
