'use client';
import { useEffect, useState } from 'react';
import { Download, RefreshCw, Trash2 } from 'lucide-react';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Header, Footer } from '@/components/music-finder';
import { csvCell, safeLink } from '@/lib/contracts';
import { platformLabels, type LicenseNote } from '@/lib/creator';
import { creatorRequest, downloadReport } from '@/lib/creator-client';
export function LicenseNotebook() {
  const [notes, setNotes] = useState<LicenseNote[]>([]), [error, setError] = useState(''), [loading, setLoading] = useState(true);
  async function load() { setLoading(true); setError(''); try { const r = await creatorRequest<{ library: LicenseNote[] }>('/api/creator'); setNotes(r.library); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load notes.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  async function remove(id: string) { try { await creatorRequest('/api/creator?noteId=' + encodeURIComponent(id), { method: 'DELETE' }); setNotes(previous => previous.filter(n => n.id !== id)); } catch (e) { setError(e instanceof Error ? e.message : 'Could not delete note.'); } }
  function exportNotes() { const rows = [['Title','Artist','Platform','License note','Evidence URL','Attribution'], ...notes.map(n => [n.song.title,n.song.artist,platformLabels[n.platform],n.notes,n.url,n.attribution])]; downloadReport('music-license-notebook.csv', '\uFEFF' + rows.map(r => r.map(csvCell).join(',')).join('\r\n'), 'text/csv;charset=utf-8'); }
  return <div className="shell"><Header/><main className="notebook-page"><div className="section-head"><div><span className="eyebrow">Your browser's collection</span><h1>License notebook</h1><p className="muted">Reusable evidence notes for the recordings you work with.</p></div><div className="row"><button className="btn ghost" disabled={loading} onClick={() => void load()} aria-label="Refresh license notebook"><RefreshCw size={17}/></button><button className="btn secondary" disabled={!notes.length} onClick={exportNotes}><Download size={17}/>Export</button></div></div>
    <p className="report-scope">A saved note is your record of a license, not verified clearance. Check the platform, channel, recording, expiry and license terms before using it in another project.</p>
    {error && <div className="notice error" role="alert">{error}</div>}{loading ? <p role="status">Loading notes…</p> : notes.length ? <div className="notebook-list">{notes.map(n => <article className="panel notebook-note" key={n.id}><div className="row between"><div><h2>{n.song.title}</h2><p className="muted">{n.song.artist} · {platformLabels[n.platform]}</p></div><AlertDialog><AlertDialogTrigger asChild><button className="btn ghost" aria-label={'Delete note for ' + n.song.title}><Trash2 size={16}/></button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Delete this reusable note?</AlertDialogTitle><AlertDialogDescription>Review decisions already saved in projects are kept. Export the notebook first if you need a copy.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep note</AlertDialogCancel><AlertDialogAction onClick={() => void remove(n.id)}>Delete note</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div><p className="notebook-text">{n.notes}</p>{safeLink(n.url) && <a className="text-action" href={n.url} target="_blank" rel="noopener noreferrer">Open license evidence</a>}{n.attribution && <div className="guide-answer"><span className="eyebrow">Saved attribution</span><p>{n.attribution}</p></div>}</article>)}</div> : <div className="empty-box"><strong>No reusable license notes yet.</strong><p>Open a recording's review, choose License noted, enter your evidence and select Keep this note in my reusable license notebook.</p><a className="btn" href="/">Open creator studio</a></div>}
    <p className="small muted">Up to 100 notes, retained for one year since their last update. Export a copy before clearing cookies or changing browsers. Projects remain available for 7 days.</p>
  </main><Footer/></div>;
}
