'use client';
import { useCallback, useEffect, useRef, useState } from 'react';
import { AudioLines, ArrowUpRight, Bookmark, Check, CircleHelp, Clock3, Download, ExternalLink, FileAudio, Headphones, Link2, LoaderCircle, Mic, Monitor, Music2, Search, ShieldCheck, SlidersHorizontal, Square, Upload, Volume2, X } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Toaster } from '@/components/ui/sonner';
import { toast } from 'sonner';
import { csvCell, secondsLabel, type Configuration, type Song } from '@/lib/contracts';
import { decodeAudio, prepareClip } from '@/lib/audio';
import { ClipWorkbench, type ClipPreview } from '@/components/clip-workbench';
import { DEFAULT_CLIP_SETTINGS, type ClipSettings } from '@/lib/clip-processing';
import { SongCard } from '@/components/song-card';
import { ScanWorkspace } from '@/components/scan-workspace';
import { creatorRequest } from '@/lib/creator-client';
import { Header, Footer } from '@/components/site-frame';
import { TesterAccess } from '@/components/tester-access';

const api = creatorRequest;
export function MusicFinder(){
 const [mode,setMode]=useState('listen');const [configuration,setConfiguration]=useState<Configuration|null>(null);const [configError,setConfigError]=useState(false);
 const [busy,setBusy]=useState('');const [error,setError]=useState('');const [message,setMessage]=useState('');
 const [query,setQuery]=useState('');const [link,setLink]=useState('');const [linkStart,setLinkStart]=useState(0);const [results,setResults]=useState<Song[]>([]);const [resultHeading,setResultHeading]=useState('');
 const [saved,setSaved]=useState<Song[]>([]);const [savedError,setSavedError]=useState('');
 const [audio,setAudio]=useState<AudioBuffer|null>(null);const [fileName,setFileName]=useState('');const [clipSettings,setClipSettings]=useState<ClipSettings>({...DEFAULT_CLIP_SETTINGS});const [clipPreview,setClipPreview]=useState<ClipPreview|null>(null);
 const [fileHash,setFileHash]=useState('');const [sourceURL,setSourceURL]=useState('');const sourceObject=useRef('');
 const [dragging,setDragging]=useState(false);const [recording,setRecording]=useState(false);const [seconds,setSeconds]=useState(0);const [tabSupported,setTabSupported]=useState(false);
 const input=useRef<HTMLInputElement>(null);const recorder=useRef<MediaRecorder|null>(null);const stream=useRef<MediaStream|null>(null);const timer=useRef<ReturnType<typeof setInterval>|null>(null);const timeout=useRef<ReturnType<typeof setTimeout>|null>(null);const isMounted=useRef(true);const lock=useRef(false);
 const requestAbort=useRef<AbortController|null>(null);const previewObject=useRef('');
 const refreshSaved=useCallback(async()=>{try{const r=await api<{songs:Song[]}>('/api/saved');setSaved(r.songs);setSavedError('');}catch(e){setSavedError(e instanceof Error?e.message:'Could not load saved finds.');}},[]);
 useEffect(()=>{isMounted.current=true;setTabSupported(!!navigator.mediaDevices?.getDisplayMedia);api<Configuration>('/api/config').then(setConfiguration).catch(()=>setConfigError(true));void refreshSaved();return()=>{isMounted.current=false;requestAbort.current?.abort();if(timer.current)clearInterval(timer.current);if(timeout.current)clearTimeout(timeout.current);if(recorder.current?.state==='recording'){recorder.current.onstop=null;recorder.current.stop();}stream.current?.getTracks().forEach(t=>t.stop());if(previewObject.current)URL.revokeObjectURL(previewObject.current);if(sourceObject.current)URL.revokeObjectURL(sourceObject.current);};},[refreshSaved]);
 const searchSongs=useCallback(async(term:string)=>{
  if(term.trim().length<2||term.length>100)throw new Error('Enter at least two characters of a song or artist.');
  if(lock.current)throw new Error('Wait for the current action to finish.');lock.current=true;setBusy('Searching the catalog…');setError('');setMessage('');setMode('search');setQuery(term);
  try{const r=await api<{songs:Song[]}>('/api/search?q='+encodeURIComponent(term));setResults(r.songs);setResultHeading(`Results for “${term}”`);if(!r.songs.length)setMessage('No catalog results. Try fewer words, a different spelling, or the artist name.');return {count:r.songs.length,songs:r.songs};}
  finally{lock.current=false;setBusy('');}
 },[]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifecycle=new AbortController();
  try{void Promise.resolve(context.registerTool({name:'search_song_catalog',title:'Search songs and artists',description:'Search the music catalog and display results on this page. Does not perform audio recognition or save a song.',inputSchema:{type:'object',properties:{query:{type:'string',minLength:2,maxLength:100}},required:['query'],additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:async(input:unknown)=>{if(!input||typeof input!=='object'||!('query'in input)||typeof input.query!=='string')throw new Error('A text query is required.');return searchSongs(input.query);}}, {signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();
 },[searchSongs]);
 const fail=(e:unknown)=>setError(e instanceof Error?e.message:'Something went wrong. Please try again.');
 async function acceptFile(file:Blob,name:string){
  if(lock.current)return;lock.current=true;setBusy('Preparing your clip…');setError('');setMessage('');
  try{const decoded=await decodeAudio(file);const bytes=crypto.subtle?await crypto.subtle.digest('SHA-256',await file.arrayBuffer()):null;if(!isMounted.current)return;setFileHash(bytes?Array.from(new Uint8Array(bytes),c=>c.toString(16).padStart(2,'0')).join(''):'');setAudio(decoded);setFileName(name);setClipSettings({...DEFAULT_CLIP_SETTINGS});setClipPreview(null);if(previewObject.current)URL.revokeObjectURL(previewObject.current);if(sourceObject.current)URL.revokeObjectURL(sourceObject.current);sourceObject.current=URL.createObjectURL(file);setSourceURL(sourceObject.current);previewObject.current='';setMode('upload');}
  catch(e){fail(e);}finally{setBusy('');lock.current=false;}
 }
 function stopRecording(){if(timeout.current)clearTimeout(timeout.current);if(timer.current)clearInterval(timer.current);if(recorder.current?.state==='recording')recorder.current.stop();stream.current?.getTracks().forEach(t=>t.stop());setRecording(false);}
 async function record(tab=false){
  if(recording){stopRecording();return;}if(lock.current)return;lock.current=true;setBusy('Waiting for permission…');setError('');setMessage('');
  let media:MediaStream|undefined;
  try{
   if(!navigator.mediaDevices || typeof MediaRecorder==='undefined')throw new Error('Recording is unavailable in this browser. Upload an audio clip instead.');
   media=tab?await navigator.mediaDevices.getDisplayMedia({video:true,audio:true}):await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});
   if(!media.getAudioTracks().length)throw new Error('No audio was shared. Choose a browser tab and enable “Share tab audio”.');
   stream.current=media;const type=['audio/webm;codecs=opus','audio/mp4','audio/webm'].find(t=>MediaRecorder.isTypeSupported(t));
   const rec=new MediaRecorder(new MediaStream(media.getAudioTracks()),type?{mimeType:type}:undefined);recorder.current=rec;const chunks:Blob[]=[];
   rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data);};rec.onerror=()=>{stopRecording();setError('Recording stopped unexpectedly. Please try again.');};
   rec.onstop=()=>{media?.getTracks().forEach(t=>t.stop());if(timer.current)clearInterval(timer.current);if(timeout.current)clearTimeout(timeout.current);if(isMounted.current){setRecording(false);lock.current=false;void acceptFile(new Blob(chunks,{type:rec.mimeType}),tab?'Browser tab recording':'Microphone recording');}};
   media.getAudioTracks()[0].onended=()=>stopRecording();rec.start();setSeconds(0);setRecording(true);setBusy('');const began=Date.now();timer.current=setInterval(()=>setSeconds(Math.min(12,(Date.now()-began)/1000)),100);timeout.current=setTimeout(stopRecording,12000);
  }catch(e){media?.getTracks().forEach(t=>t.stop());if(e instanceof DOMException&&e.name==='NotAllowedError')setError('Permission was not granted. You can try recording again or upload a file.');else fail(e);setBusy('');}finally{lock.current=false;}
 }
 async function identify(){
  if(lock.current||recording)return;
  if(!configuration?.recognition){setError('Audio identification is not active yet. Your clip stays on this device. Try song and artist search.');return;}
  if(mode!=='link'&&!audio)return;lock.current=true;setError('');setMessage('');setResults([]);setResultHeading('Your match');
  const controller=new AbortController();requestAbort.current=controller;const matches:Song[]=[];
  try{
   const offsets=[clipSettings.start];
   for(const offset of offsets){
    if(controller.signal.aborted)break;setBusy('Finding your song…');
    const options:RequestInit={method:'POST',headers:{'Idempotency-Key':crypto.randomUUID()},signal:controller.signal};
    if(mode==='link'){options.headers={...options.headers,'Content-Type':'application/json'};options.body=JSON.stringify({url:link,startSeconds:linkStart});}
    else{options.body=await prepareClip(audio!,offset,clipSettings.speed,clipSettings.normalize,12,false,clipSettings);options.headers={...options.headers,'Content-Type':'audio/wav','X-Sample-Start':String(offset)};}
    const r=await api<{song:Song|null}>('/api/recognize',options);
    if(r.song){matches.push(r.song);setResults([...matches]);}
   }
   if(!controller.signal.aborted)setMessage(matches.length?'Match saved to your finds.':'No match in this section. Try a clearer part with less talking, or adjust the speed for a remix.');
   void refreshSaved();
   void api<Configuration>('/api/config').then(setConfiguration).catch(()=>{});
  }catch(e){if(!controller.signal.aborted)fail(e);else setMessage('Scan stopped. Any completed sections are kept.');}finally{lock.current=false;setBusy('');requestAbort.current=null;}
 }
 async function save(song:Song){try{await api('/api/saved',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(song)});await refreshSaved();toast.success('Added to your saved finds.');}catch(e){toast.error(e instanceof Error?e.message:'Could not save song.');}}
 async function clearSaved(){try{await api('/api/saved',{method:'DELETE'});setSaved([]);toast.success('Saved finds cleared.');}catch(e){toast.error(e instanceof Error?e.message:'Could not clear finds.');}}
 function exportCSV(){const lines=[['Title','Artist','Album','Source','Sample at (seconds)','Apple Music','Spotify'],...saved.map(s=>[s.title,s.artist,s.album||'',s.source,s.sampleAt??'',s.apple||'',s.spotify||''])];const u=URL.createObjectURL(new Blob(['\uFEFF'+lines.map(r=>r.map(csvCell).join(',')).join('\r\n')],{type:'text/csv;charset=utf-8;'}));const a=document.createElement('a');a.href=u;a.download='whatsong-saved-finds.csv';a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
 async function prepareEdit(download=false){
  if(!audio||lock.current)return;lock.current=true;setBusy(download?'Preparing your download…':'Preparing preview…');setError('');
  try{
   const clip=await prepareClip(audio,clipSettings.start,clipSettings.speed,clipSettings.normalize,12,false,clipSettings);
   if(!isMounted.current)return;
   if(previewObject.current)URL.revokeObjectURL(previewObject.current);
   previewObject.current=URL.createObjectURL(clip);setClipPreview({url:previewObject.current,settingsKey:JSON.stringify(clipSettings)});
   if(download)toast.success('Prepared WAV is ready. Choose Download clip to save it.');
   else toast.success('Prepared clip is ready to play.');
  }catch(e){fail(e);}finally{lock.current=false;setBusy('');}
 }
 const scanBusy=useCallback((running:boolean)=>{lock.current=running;setBusy(running?'Scanning your recording…':'');},[]);
 function chooseMode(v:string){if(recording)stopRecording();setMode(v);setError('');setMessage('');}
 return <div className="shell"><Header/><main id="main-content"><section className="intro"><div><span className="eyebrow">Single-song finder</span><h1>Find the song in your clip.</h1><p>Record up to 12 seconds, upload a clip, or start from a public link.</p></div><span className="pill"><Headphones size={14}/> Free tools · no app to install</span></section>
 {configError&&<div className="notice error" role="alert">We could not connect to the service. Refresh the page to try again.</div>}
 {configuration&&!configuration.recognition&&<div className="notice" role="status"><strong>Early access:</strong> audio matching is awaiting activation. Prepare clips, plan a timeline scan, or try song and artist search.</div>}
 <input ref={input} type="file" className="sr-only" aria-label="Choose audio or video file" accept="audio/*,video/mp4,video/webm,video/quicktime,.m4a,.flac,.mov" onChange={e=>{const f=e.target.files?.[0];if(f)void acceptFile(f,f.name);e.target.value='';}}/><div className="workspace" id="finder"><section className="panel finder" aria-label="Music finder"><Tabs value={mode} onValueChange={chooseMode}><TabsList className="mode-tabs" aria-label="Find music by"><TabsTrigger className="mode-tab" value="listen" disabled={!!busy}><Mic/> Listen</TabsTrigger><TabsTrigger className="mode-tab" value="upload" disabled={!!busy}><Upload/> Upload</TabsTrigger><TabsTrigger className="mode-tab" value="link" disabled={!!busy}><Link2/> Link</TabsTrigger><TabsTrigger className="mode-tab" value="search" disabled={!!busy}><Search/> Search</TabsTrigger></TabsList>
 <TabsContent value="listen" className="mode-body"><div className="listen-surface"><button className={`listen-button ${recording?'recording':''}`} onClick={()=>record()} disabled={!!busy} aria-label={recording?'Stop recording':'Record 12 seconds'}>{recording?<Square size={36}/>:<AudioLines size={49} strokeWidth={1.7}/>}</button><h2>{recording?'Listening…':'Catch the song around you'}</h2><p className="muted small">{recording?`${seconds.toFixed(1)} / 12 seconds · tap to stop`:'Tap to record up to 12 seconds of music.'}</p>{tabSupported&&<button className="btn ghost" style={{marginTop:20}} onClick={()=>record(true)} disabled={!!busy||recording}><Monitor size={16}/> Record a browser tab</button>}<p className="micro muted" style={{marginTop:18}}>Your microphone only turns on when you ask.</p></div></TabsContent>
 <TabsContent value="upload" className="mode-body"><div className={`dropzone ${dragging?'drag':''}`} onDragOver={e=>{e.preventDefault();setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);const f=e.dataTransfer.files[0];if(f)void acceptFile(f,f.name);}}><Upload size={28} style={{margin:'auto',color:'var(--primary)'}}/><h2>{audio?'Try another clip':'Choose a section with clear music'}</h2><p>Drop audio or video here, or choose a file.</p><button className="btn secondary" onClick={()=>input.current?.click()} disabled={!!busy}>Browse files</button><p className="micro">MP3, WAV, M4A, FLAC, MP4, WebM · up to 40 MB</p></div>
 {audio&&<ClipWorkbench audio={audio} filename={fileName} sourceURL={sourceURL} settings={clipSettings} preview={clipPreview} locked={!!busy||recording} recognition={!!configuration?.recognition} onChange={setClipSettings} onPreview={()=>void prepareEdit()} onDownload={()=>void prepareEdit(true)} onIdentify={()=>void identify()}/>}</TabsContent>
 <TabsContent value="link" className="mode-body"><div className="row" style={{margin:'6px 0 18px',color:'var(--primary)'}}><Link2 size={26}/><h2 style={{fontSize:22,color:'var(--foreground)',margin:0}}>Follow the link to the song</h2></div><p className="muted small">Paste a public YouTube, TikTok, Instagram, SoundCloud, or direct media link. Each scan checks 12 seconds at your chosen start time.</p><form onSubmit={e=>{e.preventDefault();void identify();}}><label className="field-label" htmlFor="media-link">Video or audio URL</label><input id="media-link" className="field" type="url" value={link} onChange={e=>setLink(e.target.value)} placeholder="https://www.youtube.com/watch?v=…" required maxLength={1800}/><label className="field-label" htmlFor="link-start" style={{marginTop:16}}>Start time (seconds)</label><input id="link-start" className="field" type="number" min="0" max="7200" step="1" value={linkStart} onChange={e=>setLinkStart(Number(e.target.value))}/><p className="small muted">For a quiet intro, try 30 or 60 seconds. One section uses one scan.</p><button className="btn full" style={{marginTop:16}} disabled={!!busy||!configuration?.recognition||!link}><Search size={16}/> Identify from link</button></form><div className="divider"/><p className="small"><strong>Video link unavailable?</strong></p><p className="muted small">Private or restricted videos may not be accessible. Upload a short clip, or record audio from another browser tab on desktop.</p><button className="btn ghost" onClick={()=>chooseMode('listen')}><Monitor size={15}/> Go to recording</button></TabsContent>
 <TabsContent value="search" className="mode-body"><div className="row" style={{margin:'6px 0 18px',color:'var(--primary)'}}><Search size={26}/><h2 style={{fontSize:22,color:'var(--foreground)',margin:0}}>Remember a name?</h2></div><p className="muted small">Search a song title, artist, or a few words from the title.</p><form onSubmit={e=>{e.preventDefault();void searchSongs(query).catch(fail);}}><label className="field-label" htmlFor="song-query">Song or artist</label><div className="search-row"><input id="song-query" className="field" placeholder="e.g. I Wish You Love" value={query} onChange={e=>setQuery(e.target.value)} minLength={2} maxLength={100} required/><button className="btn" disabled={!!busy}><Search size={16}/> Search</button></div></form><div className="divider"/><span className="eyebrow">A place to start</span><div className="row" style={{flexWrap:'wrap',marginTop:15}}>{['I Wish You Love','Autumn Leaves','Mas Que Nada'].map(q=><button key={q} className="btn ghost" onClick={()=>void searchSongs(q).catch(fail)} disabled={!!busy}>{q}</button>)}</div><p className="micro muted" style={{marginTop:28}}>Catalog results from iTunes. Search suggestions are not audio matches.</p></TabsContent>
 </Tabs><div className="trust"><span className="row"><ShieldCheck size={14}/> No full files stored</span><span>{configuration?.tester?'Tester mode · unlimited app quota':configuration?.recognition?`${configuration.dailyLimit} free scans per 24 hours`:'No account needed'}</span><TesterAccess configuration={configuration} disabled={!!busy||recording} onChange={setConfiguration}/></div></section>
 <aside className="panel side"><span className="eyebrow">A better chance of a match</span><h2>Start with the clearest section.</h2><div className="tip"><Headphones size={20}/><div><h3>Let the music lead</h3><p>A chorus or clear instrumental section works better than talking or applause.</p></div></div><div className="tip"><SlidersHorizontal size={20}/><div><h3>Check the original recording</h3><p>Original-speed audio is the best starting point. Speed adjustments can help with some edits; remixes may remain unmatched.</p></div></div><div className="tip"><Bookmark size={20}/><div><h3>Keep the good ones</h3><p>Save finds here, then listen on Apple Music, Spotify or YouTube.</p></div></div><div className="divider"/><a href="/how-it-works" className="row small">More ways to find a song</a></aside></div>
 <div aria-live="polite" aria-atomic="true" style={{marginTop:20}}>{busy&&<div className="notice row between"><span className="row"><LoaderCircle className="animate-spin" size={18}/>{busy}</span>{requestAbort.current&&<button className="btn ghost" onClick={()=>requestAbort.current?.abort()}>Stop</button>}</div>}{error&&<div className="notice error" role="alert">{error}</div>}{message&&<div className="notice">{message}</div>}</div>
 {resultHeading&&<section className="section" aria-label="Search results"><div className="section-head"><h2>{resultHeading}</h2><span className="muted small">{results.length} {results.length===1?'result':'results'}</span></div><div className="result-grid">{results.map((song,i)=><SongCard key={song.id+':'+i} song={song} onSave={save} saved={saved.some(s=>s.id===song.id)}/>)}</div></section>}
 <ScanWorkspace audio={audio} sourceURL={sourceURL} fileHash={fileHash} filename={fileName} configuration={configuration} locked={!!busy||recording} onChooseFile={()=>{setMode('upload');input.current?.click();}} onBusyChange={scanBusy} onComplete={refreshSaved}/>
 {configuration?.sponsor&&<aside className="ad-slot" aria-label="Advertisement"><span className="eyebrow">Advertisement</span><p>{configuration.sponsor.description}</p><a className="btn ghost" href={configuration.sponsor.url} rel="sponsored noopener noreferrer" target="_blank">{configuration.sponsor.label}</a></aside>}
 <section className="section" id="saved"><div className="section-head"><div><span className="eyebrow">This browser’s collection</span><h2>Saved finds <span className="muted small">{saved.length?`(${saved.length})`:''}</span></h2></div>{saved.length>0&&<div className="row"><button className="btn ghost" onClick={exportCSV} aria-label="Export saved finds as CSV"><Download size={16}/><span className="small">Export</span></button><AlertDialog><AlertDialogTrigger asChild><button className="btn ghost" aria-label="Clear all saved finds"><X size={16}/></button></AlertDialogTrigger><AlertDialogContent><AlertDialogHeader><AlertDialogTitle>Clear your saved finds?</AlertDialogTitle><AlertDialogDescription>This removes this browser's saved collection from our servers. Export it first if you want a copy.</AlertDialogDescription></AlertDialogHeader><AlertDialogFooter><AlertDialogCancel>Keep finds</AlertDialogCancel><AlertDialogAction onClick={clearSaved}>Clear finds</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog></div>}</div>{savedError?<div className="notice error">{savedError} <button className="btn ghost" onClick={refreshSaved}>Retry</button></div>:saved.length?<><div className="result-grid">{saved.map(s=><SongCard key={s.id} song={s}/>)}</div><p className="micro muted">Linked to this browser with a private cookie. Up to 100 finds, retained for one year. Clearing cookies removes access.</p></>:<div className="empty-box"><Bookmark size={24} style={{margin:'0 auto 10px',color:'var(--text-subtle)'}}/><strong style={{display:'block',color:'var(--foreground)'}}>Good songs deserve a second listen.</strong><p className="small" style={{marginBottom:0}}>Your matches and songs you save will appear here.</p></div>}</section>
 </main><Footer/><Toaster theme="dark"/></div>
}
