'use client';
import { useEffect, useState } from 'react';
import { Header, Footer } from '@/components/music-finder';
import { creatorRequest, downloadReport } from '@/lib/creator-client';
import { clearTesterKey, setTesterKey } from '@/lib/tester-client';
type Insights = { periodDays: number; events: { kind: string; value: string; count: number; visitors: number }[]; jobs: { projects: number; sections: number; matched: number; no_match: number; unresolved: number }; last24Hours: { kind: string; requests: number; finished: number }[]; cumulativeMeters: { id: string; used: number }[]; returning: { visitors: number }; aiEnabled: boolean; notes: string[] };
export function ProductInsights() {
  const [data, setData] = useState<Insights | null>(null), [error, setError] = useState(''), [loading, setLoading] = useState(true), [key, setKey] = useState('');
  async function load() { setLoading(true); setError(''); try { setData(await creatorRequest<Insights>('/api/insights')); } catch (e) { setError(e instanceof Error ? e.message : 'Could not load metrics.'); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, []);
  const visitors = data?.events.find(e => e.kind === 'studio_opened')?.visitors || 0;
  const reportUsers = data?.events.filter(e => e.kind === 'report_opened').reduce((n,e) => n + e.visitors, 0) || 0;
  const exports = data?.events.filter(e => e.kind === 'report_exported').reduce((n,e) => n + e.count, 0) || 0;
  return <div className="shell"><Header/><main className="notebook-page"><div className="section-head"><div><span className="eyebrow">Operator workspace</span><h1>Product measurements</h1><p className="muted">Use observed behavior to decide the next product change.</p></div><button className="btn ghost" disabled={loading} onClick={() => void load()}>Refresh</button></div>
    {error && <div className="notice error" role="alert">{error}</div>}{!data && !loading && <form className="panel operator-login" onSubmit={e => { e.preventDefault(); setTesterKey(key); setKey(''); void load(); }}><label className="field-label" htmlFor="operator-key">Tester access key</label><div className="search-row"><input id="operator-key" className="field" type="password" autoComplete="off" value={key} onChange={e => setKey(e.target.value)} required/><button className="btn">Enable operator access</button></div></form>}
    {loading && <p role="status">Loading measurements…</p>}{data && <><div className="report-metrics"><div><strong>{visitors}</strong><span>studio collections · 30 days</span></div><div><strong>{reportUsers}</strong><span>opened a report</span></div><div><strong>{exports}</strong><span>report exports</span></div><div><strong>{data.returning.visitors}</strong><span>returned on another day</span></div></div><h2>Recent scan outcomes</h2><p>{data.jobs.projects} retained projects · {data.jobs.sections} sections · {data.jobs.matched} matches returned · {data.jobs.no_match} no matches · {data.jobs.unresolved} unresolved</p><p className="small muted">Returned matches are not a measure of recognition accuracy.</p><div className="insights-table-wrap"><table className="insights-table"><thead><tr><th>Event</th><th>Detail</th><th>Count</th><th>Browser collections</th></tr></thead><tbody>{data.events.map(e => <tr key={e.kind + ':' + e.value}><td>{e.kind.replaceAll('_',' ')}</td><td>{e.value || '—'}</td><td>{e.count}</td><td>{e.visitors}</td></tr>)}</tbody></table></div><h2>Provider reservations in the last 24 hours</h2>{data.last24Hours.map(r => <p key={r.kind}>{r.kind}: {r.requests} reserved · {r.finished} settled responses</p>)}<p>GPT writing: {data.aiEnabled ? 'enabled' : 'not enabled'}.</p><div className="notice">{data.notes.map(n => <p key={n}>{n}</p>)}</div><div className="row"><button className="btn secondary" onClick={() => downloadReport('creator-product-metrics.json', JSON.stringify(data,null,2), 'application/json')}>Export metrics</button><button className="btn ghost" onClick={() => { clearTesterKey(); setData(null); setError('Operator access disabled.'); }}>Exit tester mode</button></div></>}
  </main><Footer/></div>;
}
